os: linux
dist: trusty
sudo: required
env:
  global:
    - CC_TEST_REPORTER_ID=64ab1accbafee2ecad636528fa5a52934e5e895ca9d3e90e0a7450362a7db749
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
- codecov
